title: Nengi Harry
logo: ![profilephoto](https://user-images.githubusercontent.com/7488991/74596647-a7ecb800-5017-11ea-9894-8760e212b099.JPG)
description: Nengi Harry's Data Science Portfolio
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
